services:
  app:
    build: .
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_started
      mysql:
        condition: service_healthy
  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"
    command: ["mongod", "--bind_ip_all"]
    volumes:
      - mongo-data:/data/db
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: taiwo0277
      MYSQL_DATABASE: fakestore_api
    volumes:
      - mysql_data:/data/db/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ptaiwo0277"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mongo-data:
  mysql_data: